"""add company_user_invitations and company_talent_pool tables

Revision ID: 1056ca1c18fa
Revises: 85d66f225618
Create Date: 2025-11-09 10:38:58.643772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1056ca1c18fa'
down_revision: Union[str, Sequence[str], None] = '85d66f225618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_talent_pool',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('source_application_id', sa.String(length=36), nullable=True),
    sa.Column('source_position_id', sa.String(length=36), nullable=True),
    sa.Column('added_reason', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('added_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_talent_pool_candidate_id'), 'company_talent_pool', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_company_talent_pool_company_id'), 'company_talent_pool', ['company_id'], unique=False)
    op.create_index('ix_company_talent_pool_rating', 'company_talent_pool', ['rating'], unique=False)
    op.create_index('ix_company_talent_pool_status', 'company_talent_pool', ['status'], unique=False)
    op.create_table('company_user_invitations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('invited_by_user_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['company_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token', name='uq_invitation_token')
    )
    op.create_index(op.f('ix_company_user_invitations_company_id'), 'company_user_invitations', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_user_invitations_email'), 'company_user_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_company_user_invitations_id'), 'company_user_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_company_user_invitations_token'), 'company_user_invitations', ['token'], unique=True)
    op.create_index('ix_invitation_email', 'company_user_invitations', ['email'], unique=False)
    op.create_index('ix_invitation_email_company', 'company_user_invitations', ['email', 'company_id'], unique=False)
    op.create_index('ix_invitation_token', 'company_user_invitations', ['token'], unique=False)
    # Note: company_roles and company_user_company_roles tables exist and should not be dropped
    # Note: job_position_stages indexes changes are handled separately
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invitation_token', table_name='company_user_invitations')
    op.drop_index('ix_invitation_email_company', table_name='company_user_invitations')
    op.drop_index('ix_invitation_email', table_name='company_user_invitations')
    op.drop_index(op.f('ix_company_user_invitations_token'), table_name='company_user_invitations')
    op.drop_index(op.f('ix_company_user_invitations_id'), table_name='company_user_invitations')
    op.drop_index(op.f('ix_company_user_invitations_email'), table_name='company_user_invitations')
    op.drop_index(op.f('ix_company_user_invitations_company_id'), table_name='company_user_invitations')
    op.drop_table('company_user_invitations')
    op.drop_index('ix_company_talent_pool_status', table_name='company_talent_pool')
    op.drop_index('ix_company_talent_pool_rating', table_name='company_talent_pool')
    op.drop_index(op.f('ix_company_talent_pool_company_id'), table_name='company_talent_pool')
    op.drop_index(op.f('ix_company_talent_pool_candidate_id'), table_name='company_talent_pool')
    op.drop_table('company_talent_pool')
    # ### end Alembic commands ###
