"""initial_schema_consolidated

Revision ID: 33aae23e0ca8
Revises: 
Create Date: 2025-11-07 10:47:05.122954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33aae23e0ca8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'COMPLETE', 'DELETED', name='candidatestatusenum'), nullable=False),
    sa.Column('job_category', sa.Enum('TECHNOLOGY', 'OPERATIONS', 'SALES', 'MARKETING', 'ADMINISTRATION', 'HR', 'FINANCE', 'CUSTOMER_SERVICE', 'OTHER', name='jobcategoryenum'), nullable=False),
    sa.Column('candidate_type', sa.Enum('BASIC', 'EXTENDED', 'PREMIUM', name='candidatetypeenum'), nullable=False),
    sa.Column('expected_annual_salary', sa.Integer(), nullable=True),
    sa.Column('current_annual_salary', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('relocation', sa.Boolean(), nullable=True),
    sa.Column('work_modality', sa.JSON(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('other_languages', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('data_consent', sa.Boolean(), nullable=True),
    sa.Column('data_consent_on', sa.Date(), nullable=True),
    sa.Column('current_roles', sa.JSON(), nullable=True),
    sa.Column('expected_roles', sa.JSON(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('created_on', sa.Date(), nullable=False),
    sa.Column('updated_on', sa.Date(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('candidate_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.create_index(op.f('ix_candidates_name'), 'candidates', ['name'], unique=False)
    op.create_index(op.f('ix_candidates_user_id'), 'candidates', ['user_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', name='companystatusenum', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_table('company_phases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('workflow_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('default_view', sa.Enum('KANBAN', 'LIST', name='defaultview'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='phasestatus'), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_phases_company_id'), 'company_phases', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_phases_id'), 'company_phases', ['id'], unique=False)
    op.create_index(op.f('ix_company_phases_sort_order'), 'company_phases', ['sort_order'], unique=False)
    op.create_index(op.f('ix_company_phases_status'), 'company_phases', ['status'], unique=False)
    op.create_index(op.f('ix_company_phases_workflow_type'), 'company_phases', ['workflow_type'], unique=False)
    op.create_table('entity_customizations',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('validation', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_entity_customizations_entity_type_id')
    )
    op.create_index(op.f('ix_entity_customizations_entity_id'), 'entity_customizations', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_customizations_entity_type'), 'entity_customizations', ['entity_type'], unique=False)
    op.create_index('ix_entity_customizations_entity_type_id', 'entity_customizations', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_entity_customizations_id'), 'entity_customizations', ['id'], unique=False)
    op.create_table('field_validation_rules',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('custom_field_id', sa.String(length=255), nullable=False),
    sa.Column('stage_id', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('comparison_operator', sa.String(length=50), nullable=False),
    sa.Column('position_field_path', sa.String(length=255), nullable=True),
    sa.Column('comparison_value', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('validation_message', sa.Text(), nullable=False),
    sa.Column('auto_reject', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_validation_rules_custom_field_id'), 'field_validation_rules', ['custom_field_id'], unique=False)
    op.create_index(op.f('ix_field_validation_rules_is_active'), 'field_validation_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_field_validation_rules_stage_id'), 'field_validation_rules', ['stage_id'], unique=False)
    op.create_table('interview_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('intro', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('EXTENDED_PROFILE', 'POSITION_INTERVIEW', name='interviewtemplatetypeenum'), nullable=False),
    sa.Column('status', sa.Enum('ENABLED', 'DRAFT', 'DISABLED', name='interviewtemplatestatusenum'), nullable=False),
    sa.Column('job_category', sa.Enum('TECHNOLOGY', 'OPERATIONS', 'SALES', 'MARKETING', 'ADMINISTRATION', 'HR', 'FINANCE', 'CUSTOMER_SERVICE', 'OTHER', name='jobcategoryenum'), nullable=True),
    sa.Column('allow_ai_questions', sa.Boolean(), nullable=False),
    sa.Column('legal_notice', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('template_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_created_by_status', 'interview_templates', ['created_by', 'status'], unique=False)
    op.create_index('idx_job_category_status', 'interview_templates', ['job_category', 'status'], unique=False)
    op.create_index('idx_status_type', 'interview_templates', ['status', 'type'], unique=False)
    op.create_index('idx_type', 'interview_templates', ['type'], unique=False)
    op.create_index(op.f('ix_interview_templates_created_by'), 'interview_templates', ['created_by'], unique=False)
    op.create_index(op.f('ix_interview_templates_id'), 'interview_templates', ['id'], unique=False)
    op.create_index(op.f('ix_interview_templates_job_category'), 'interview_templates', ['job_category'], unique=False)
    op.create_index(op.f('ix_interview_templates_name'), 'interview_templates', ['name'], unique=False)
    op.create_index(op.f('ix_interview_templates_status'), 'interview_templates', ['status'], unique=False)
    op.create_index(op.f('ix_interview_templates_type'), 'interview_templates', ['type'], unique=False)
    op.create_table('job_position_workflows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('default_view', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stages', sa.JSON(), nullable=False),
    sa.Column('custom_fields_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_position_workflows_company_id'), 'job_position_workflows', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_position_workflows_id'), 'job_position_workflows', ['id'], unique=False)
    op.create_index(op.f('ix_job_position_workflows_status'), 'job_position_workflows', ['status'], unique=False)
    op.create_table('job_positions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('job_position_workflow_id', sa.String(), nullable=True),
    sa.Column('stage_id', sa.String(), nullable=True),
    sa.Column('phase_workflows', sa.JSON(), nullable=True),
    sa.Column('stage_assignments', sa.JSON(), nullable=True),
    sa.Column('custom_fields_values', sa.JSON(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('job_category', sa.Enum('TECHNOLOGY', 'OPERATIONS', 'SALES', 'MARKETING', 'ADMINISTRATION', 'HR', 'FINANCE', 'CUSTOMER_SERVICE', 'OTHER', name='jobcategoryenum'), nullable=False),
    sa.Column('open_at', sa.DateTime(), nullable=True),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('public_slug', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_positions_company_id'), 'job_positions', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_positions_id'), 'job_positions', ['id'], unique=False)
    op.create_index(op.f('ix_job_positions_job_position_workflow_id'), 'job_positions', ['job_position_workflow_id'], unique=False)
    op.create_index(op.f('ix_job_positions_public_slug'), 'job_positions', ['public_slug'], unique=True)
    op.create_index(op.f('ix_job_positions_stage_id'), 'job_positions', ['stage_id'], unique=False)
    op.create_index(op.f('ix_job_positions_title'), 'job_positions', ['title'], unique=False)
    op.create_index(op.f('ix_job_positions_visibility'), 'job_positions', ['visibility'], unique=False)
    op.create_table('user_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('asset_type', sa.Enum('PDF_RESUME', 'LINKEDIN_PROFILE', 'PORTFOLIO', 'COVER_LETTER', name='assettypeenum'), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatusenum'), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('file_metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_assets_asset_type'), 'user_assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_user_assets_id'), 'user_assets', ['id'], unique=False)
    op.create_index(op.f('ix_user_assets_processing_status'), 'user_assets', ['processing_status'], unique=False)
    op.create_index(op.f('ix_user_assets_user_id'), 'user_assets', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('subscription_tier', sa.String(length=20), nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(), nullable=True),
    sa.Column('password_reset_token', sa.String(), nullable=True),
    sa.Column('password_reset_expires_at', sa.DateTime(), nullable=True),
    sa.Column('preferred_language', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('workflow_type', sa.Enum('JOB_POSITION_OPENING', 'CANDIDATE_APPLICATION', 'CANDIDATE_ONBOARDING', name='workflowtypeenum', native_enum=False, length=30), nullable=False),
    sa.Column('display', sa.Enum('KANBAN', 'LIST', name='workflowdisplayenum', native_enum=False, length=20), nullable=False),
    sa.Column('phase_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='workflowstatusenum', native_enum=False, length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_company_id'), 'workflows', ['company_id'], unique=False)
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_index(op.f('ix_workflows_is_default'), 'workflows', ['is_default'], unique=False)
    op.create_index(op.f('ix_workflows_phase_id'), 'workflows', ['phase_id'], unique=False)
    op.create_index(op.f('ix_workflows_status'), 'workflows', ['status'], unique=False)
    op.create_index(op.f('ix_workflows_workflow_type'), 'workflows', ['workflow_type'], unique=False)
    op.create_table('candidate_educations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('degree', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_educations_id'), 'candidate_educations', ['id'], unique=False)
    op.create_table('candidate_experiences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_experiences_id'), 'candidate_experiences', ['id'], unique=False)
    op.create_table('candidate_projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_projects_id'), 'candidate_projects', ['id'], unique=False)
    op.create_table('company_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'RECRUITER', 'VIEWER', name='companyuserrole', native_enum=False, length=20), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='companyuserstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'user_id', name='uq_company_user')
    )
    op.create_index(op.f('ix_company_users_company_id'), 'company_users', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_users_id'), 'company_users', ['id'], unique=False)
    op.create_index(op.f('ix_company_users_user_id'), 'company_users', ['user_id'], unique=False)
    op.create_table('company_roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_roles_id'), 'company_roles', ['id'], unique=False)
    op.create_index(op.f('ix_company_roles_company_id'), 'company_roles', ['company_id'], unique=False)
    op.create_table('company_user_company_roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_user_id', sa.String(), nullable=False),
    sa.Column('company_role_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_user_id'], ['company_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_role_id'], ['company_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_user_id', 'company_role_id', name='uq_company_user_role')
    )
    op.create_index(op.f('ix_company_user_company_roles_company_user_id'), 'company_user_company_roles', ['company_user_id'], unique=False)
    op.create_index(op.f('ix_company_user_company_roles_company_role_id'), 'company_user_company_roles', ['company_role_id'], unique=False)
    op.create_table('custom_fields',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('entity_customization_id', sa.String(length=255), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('field_config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_customization_id'], ['entity_customizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_customization_id', 'field_key', name='uq_custom_fields_entity_customization_field_key')
    )
    op.create_index('ix_custom_fields_entity_customization_id', 'custom_fields', ['entity_customization_id'], unique=False)
    op.create_index(op.f('ix_custom_fields_id'), 'custom_fields', ['id'], unique=False)
    op.create_table('interview_template_sections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('interview_template_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('intro', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('section', sa.Enum('EXPERIENCE', 'EDUCATION', 'PROJECT', 'SOFT_SKILL', 'GENERAL', name='interviewtemplatesectionenum'), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ENABLED', 'DRAFT', 'DISABLED', name='interviewtemplatesectionstatusenum'), nullable=False),
    sa.Column('allow_ai_questions', sa.Boolean(), nullable=False),
    sa.Column('allow_ai_override_questions', sa.Boolean(), nullable=False),
    sa.Column('legal_notice', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['interview_template_id'], ['interview_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_template_sections_id'), 'interview_template_sections', ['id'], unique=False)
    op.create_index(op.f('ix_interview_template_sections_interview_template_id'), 'interview_template_sections', ['interview_template_id'], unique=False)
    op.create_index(op.f('ix_interview_template_sections_section'), 'interview_template_sections', ['section'], unique=False)
    op.create_index(op.f('ix_interview_template_sections_sort_order'), 'interview_template_sections', ['sort_order'], unique=False)
    op.create_index(op.f('ix_interview_template_sections_status'), 'interview_template_sections', ['status'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('resume_type', sa.String(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('content_data', sa.JSON(), nullable=True),
    sa.Column('ai_content', sa.JSON(), nullable=True),
    sa.Column('custom_content', sa.JSON(), nullable=True),
    sa.Column('formatting_preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_candidate_id'), 'resumes', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_resumes_resume_type'), 'resumes', ['resume_type'], unique=False)
    op.create_table('workflow_stages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('stage_type', sa.Enum('SUCCESS', 'INITIAL', 'PROGRESS', 'FAIL', 'HOLD', name='workflowstagetypeenum', native_enum=False, length=20), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('allow_skip', sa.Boolean(), nullable=False),
    sa.Column('estimated_duration_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('default_role_ids', sa.JSON(), nullable=True),
    sa.Column('default_assigned_users', sa.JSON(), nullable=True),
    sa.Column('email_template_id', sa.String(length=255), nullable=True),
    sa.Column('custom_email_text', sa.Text(), nullable=True),
    sa.Column('deadline_days', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('next_phase_id', sa.String(length=255), nullable=True),
    sa.Column('kanban_display', sa.Enum('COLUMN', 'ROW', 'HIDDEN', name='kanbandisplayenum', native_enum=False, length=30), nullable=False),
    sa.Column('style', sa.JSON(), nullable=True),
    sa.Column('validation_rules', sa.JSON(), nullable=True),
    sa.Column('recommended_rules', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_stages_id'), 'workflow_stages', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_stages_order'), 'workflow_stages', ['order'], unique=False)
    op.create_index(op.f('ix_workflow_stages_workflow_id'), 'workflow_stages', ['workflow_id'], unique=False)
    op.create_table('candidate_applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('job_position_id', sa.String(), nullable=False),
    sa.Column('application_status', sa.Enum('applied', 'reviewing', 'interviewed', 'rejected', 'accepted', 'withdrawn', name='applicationstatusenum'), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('current_stage_id', sa.String(), nullable=True),
    sa.Column('stage_entered_at', sa.DateTime(), nullable=True),
    sa.Column('stage_deadline', sa.DateTime(), nullable=True),
    sa.Column('task_status', sa.Enum('pending', 'in_progress', 'completed', 'blocked', name='taskstatus'), nullable=False),
    sa.Column('current_phase_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['current_phase_id'], ['company_phases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_stage_id'], ['workflow_stages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_applications_application_status'), 'candidate_applications', ['application_status'], unique=False)
    op.create_index(op.f('ix_candidate_applications_candidate_id'), 'candidate_applications', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_applications_current_phase_id'), 'candidate_applications', ['current_phase_id'], unique=False)
    op.create_index(op.f('ix_candidate_applications_current_stage_id'), 'candidate_applications', ['current_stage_id'], unique=False)
    op.create_index(op.f('ix_candidate_applications_id'), 'candidate_applications', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_applications_job_position_id'), 'candidate_applications', ['job_position_id'], unique=False)
    op.create_table('company_candidates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_INVITATION', 'PENDING_CONFIRMATION', 'ACTIVE', 'REJECTED', 'ARCHIVED', name='companycandidatestatus', native_enum=False, length=30), nullable=False),
    sa.Column('ownership_status', sa.Enum('COMPANY_OWNED', 'USER_OWNED', name='ownershipstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_by_user_id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=True),
    sa.Column('current_stage_id', sa.String(), nullable=True),
    sa.Column('phase_id', sa.String(), nullable=True),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('visibility_settings', sa.JSON(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('internal_notes', sa.Text(), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='candidatepriority', native_enum=False, length=10), nullable=False),
    sa.Column('lead_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('resume_url', sa.String(length=500), nullable=True),
    sa.Column('resume_uploaded_by', sa.String(), nullable=True),
    sa.Column('resume_uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['company_users.id'], ),
    sa.ForeignKeyConstraint(['phase_id'], ['company_phases.id'], ),
    sa.ForeignKeyConstraint(['resume_uploaded_by'], ['company_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_candidates_candidate_id'), 'company_candidates', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_company_candidates_company_id'), 'company_candidates', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_candidates_created_by_user_id'), 'company_candidates', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_company_candidates_current_stage_id'), 'company_candidates', ['current_stage_id'], unique=False)
    op.create_index(op.f('ix_company_candidates_id'), 'company_candidates', ['id'], unique=False)
    op.create_index(op.f('ix_company_candidates_lead_id'), 'company_candidates', ['lead_id'], unique=False)
    op.create_index(op.f('ix_company_candidates_ownership_status'), 'company_candidates', ['ownership_status'], unique=False)
    op.create_index(op.f('ix_company_candidates_phase_id'), 'company_candidates', ['phase_id'], unique=False)
    op.create_index(op.f('ix_company_candidates_source'), 'company_candidates', ['source'], unique=False)
    op.create_index(op.f('ix_company_candidates_status'), 'company_candidates', ['status'], unique=False)
    op.create_index(op.f('ix_company_candidates_workflow_id'), 'company_candidates', ['workflow_id'], unique=False)
    op.create_table('field_configurations',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('entity_customization_id', sa.String(length=255), nullable=False),
    sa.Column('custom_field_id', sa.String(length=255), nullable=False),
    sa.Column('context_type', sa.String(length=50), nullable=True),
    sa.Column('context_id', sa.String(length=255), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['custom_field_id'], ['custom_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_customization_id'], ['entity_customizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_customization_id', 'custom_field_id', 'context_type', 'context_id', name='uq_field_configurations_entity_field_context')
    )
    op.create_index('ix_field_configurations_context', 'field_configurations', ['context_type', 'context_id'], unique=False)
    op.create_index(op.f('ix_field_configurations_context_id'), 'field_configurations', ['context_id'], unique=False)
    op.create_index(op.f('ix_field_configurations_context_type'), 'field_configurations', ['context_type'], unique=False)
    op.create_index('ix_field_configurations_custom_field_id', 'field_configurations', ['custom_field_id'], unique=False)
    op.create_index(op.f('ix_field_configurations_entity_customization_id'), 'field_configurations', ['entity_customization_id'], unique=False)
    op.create_index(op.f('ix_field_configurations_id'), 'field_configurations', ['id'], unique=False)
    op.create_table('interview_template_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('interview_template_section_id', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ENABLED', 'DRAFT', 'DISABLED', name='interviewtemplatequestionstatusenum'), nullable=False),
    sa.Column('data_type', sa.Enum('INT', 'DATE', 'SHORT_STRING', 'LARGE_STRING', name='interviewtemplatequestiondatatypeenum'), nullable=False),
    sa.Column('scope', sa.Enum('GLOBAL', 'ITEM', name='interviewtemplatequestionscopeenum'), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('allow_ai_followup', sa.Boolean(), nullable=False),
    sa.Column('legal_notice', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['interview_template_section_id'], ['interview_template_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_template_questions_id'), 'interview_template_questions', ['id'], unique=False)
    op.create_index(op.f('ix_interview_template_questions_interview_template_section_id'), 'interview_template_questions', ['interview_template_section_id'], unique=False)
    op.create_index(op.f('ix_interview_template_questions_status'), 'interview_template_questions', ['status'], unique=False)
    op.create_table('job_position_activities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_position_id', sa.String(), nullable=False),
    sa.Column('activity_type', sa.Enum('CREATED', 'EDITED', 'STAGE_MOVED', 'STATUS_CHANGED', 'COMMENT_ADDED', name='activitytypeenum', native_enum=False, length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('performed_by_user_id', sa.String(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_positions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['company_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_position_activities_activity_type'), 'job_position_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_job_position_activities_created_at'), 'job_position_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_position_activities_id'), 'job_position_activities', ['id'], unique=False)
    op.create_index(op.f('ix_job_position_activities_job_position_id'), 'job_position_activities', ['job_position_id'], unique=False)
    op.create_index(op.f('ix_job_position_activities_performed_by_user_id'), 'job_position_activities', ['performed_by_user_id'], unique=False)
    op.create_table('job_position_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_position_id', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=True),
    sa.Column('stage_id', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=False),
    sa.Column('review_status', sa.Enum('REVIEWED', 'PENDING', name='commentreviewstatusenum', native_enum=False, length=20), nullable=False),
    sa.Column('visibility', sa.Enum('PRIVATE', 'SHARED', name='commentvisibilityenum', native_enum=False, length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['company_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_positions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['job_position_workflows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_position_comments_created_by_user_id'), 'job_position_comments', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_job_position_comments_id'), 'job_position_comments', ['id'], unique=False)
    op.create_index(op.f('ix_job_position_comments_job_position_id'), 'job_position_comments', ['job_position_id'], unique=False)
    op.create_index(op.f('ix_job_position_comments_review_status'), 'job_position_comments', ['review_status'], unique=False)
    op.create_index(op.f('ix_job_position_comments_stage_id'), 'job_position_comments', ['stage_id'], unique=False)
    op.create_index(op.f('ix_job_position_comments_workflow_id'), 'job_position_comments', ['workflow_id'], unique=False)
    op.create_table('candidate_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_candidate_id', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=True),
    sa.Column('stage_id', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=False),
    sa.Column('review_status', sa.Enum('REVIEWED', 'PENDING', name='commentreviewstatus', native_enum=False, length=20), nullable=False),
    sa.Column('visibility', sa.Enum('PRIVATE', 'SHARED', 'SHARED_WITH_CANDIDATE', name='commentvisibility', native_enum=False, length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_candidate_id'], ['company_candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['company_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stage_id'], ['workflow_stages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_comments_company_candidate_id'), 'candidate_comments', ['company_candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_comments_created_by_user_id'), 'candidate_comments', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_candidate_comments_id'), 'candidate_comments', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_comments_review_status'), 'candidate_comments', ['review_status'], unique=False)
    op.create_index(op.f('ix_candidate_comments_stage_id'), 'candidate_comments', ['stage_id'], unique=False)
    op.create_index(op.f('ix_candidate_comments_workflow_id'), 'candidate_comments', ['workflow_id'], unique=False)
    op.create_table('custom_field_values',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('company_candidate_id', sa.String(length=255), nullable=True),
    sa.Column('values', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_candidate_id'], ['company_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_custom_field_values_entity_type_id')
    )
    op.create_index('ix_custom_field_values_company_candidate_id', 'custom_field_values', ['company_candidate_id'], unique=False)
    op.create_index(op.f('ix_custom_field_values_entity_id'), 'custom_field_values', ['entity_id'], unique=False)
    op.create_index(op.f('ix_custom_field_values_entity_type'), 'custom_field_values', ['entity_type'], unique=False)
    op.create_index('ix_custom_field_values_entity_type_id', 'custom_field_values', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_custom_field_values_id'), 'custom_field_values', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_field_values_id'), table_name='custom_field_values')
    op.drop_index('ix_custom_field_values_entity_type_id', table_name='custom_field_values')
    op.drop_index(op.f('ix_custom_field_values_entity_type'), table_name='custom_field_values')
    op.drop_index(op.f('ix_custom_field_values_entity_id'), table_name='custom_field_values')
    op.drop_index('ix_custom_field_values_company_candidate_id', table_name='custom_field_values')
    op.drop_table('custom_field_values')
    op.drop_index(op.f('ix_candidate_comments_workflow_id'), table_name='candidate_comments')
    op.drop_index(op.f('ix_candidate_comments_stage_id'), table_name='candidate_comments')
    op.drop_index(op.f('ix_candidate_comments_review_status'), table_name='candidate_comments')
    op.drop_index(op.f('ix_candidate_comments_id'), table_name='candidate_comments')
    op.drop_index(op.f('ix_candidate_comments_created_by_user_id'), table_name='candidate_comments')
    op.drop_index(op.f('ix_candidate_comments_company_candidate_id'), table_name='candidate_comments')
    op.drop_table('candidate_comments')
    op.drop_index(op.f('ix_job_position_comments_workflow_id'), table_name='job_position_comments')
    op.drop_index(op.f('ix_job_position_comments_stage_id'), table_name='job_position_comments')
    op.drop_index(op.f('ix_job_position_comments_review_status'), table_name='job_position_comments')
    op.drop_index(op.f('ix_job_position_comments_job_position_id'), table_name='job_position_comments')
    op.drop_index(op.f('ix_job_position_comments_id'), table_name='job_position_comments')
    op.drop_index(op.f('ix_job_position_comments_created_by_user_id'), table_name='job_position_comments')
    op.drop_table('job_position_comments')
    op.drop_index(op.f('ix_job_position_activities_performed_by_user_id'), table_name='job_position_activities')
    op.drop_index(op.f('ix_job_position_activities_job_position_id'), table_name='job_position_activities')
    op.drop_index(op.f('ix_job_position_activities_id'), table_name='job_position_activities')
    op.drop_index(op.f('ix_job_position_activities_created_at'), table_name='job_position_activities')
    op.drop_index(op.f('ix_job_position_activities_activity_type'), table_name='job_position_activities')
    op.drop_table('job_position_activities')
    op.drop_index(op.f('ix_interview_template_questions_status'), table_name='interview_template_questions')
    op.drop_index(op.f('ix_interview_template_questions_interview_template_section_id'), table_name='interview_template_questions')
    op.drop_index(op.f('ix_interview_template_questions_id'), table_name='interview_template_questions')
    op.drop_table('interview_template_questions')
    op.drop_index(op.f('ix_field_configurations_id'), table_name='field_configurations')
    op.drop_index(op.f('ix_field_configurations_entity_customization_id'), table_name='field_configurations')
    op.drop_index('ix_field_configurations_custom_field_id', table_name='field_configurations')
    op.drop_index(op.f('ix_field_configurations_context_type'), table_name='field_configurations')
    op.drop_index(op.f('ix_field_configurations_context_id'), table_name='field_configurations')
    op.drop_index('ix_field_configurations_context', table_name='field_configurations')
    op.drop_table('field_configurations')
    op.drop_index(op.f('ix_company_candidates_workflow_id'), table_name='company_candidates')
    op.drop_index(op.f('ix_company_candidates_status'), table_name='company_candidates')
    op.drop_index(op.f('ix_company_candidates_source'), table_name='company_candidates')
    op.drop_index(op.f('ix_company_candidates_phase_id'), table_name='company_candidates')
    op.drop_index(op.f('ix_company_candidates_ownership_status'), table_name='company_candidates')
    op.drop_index(op.f('ix_company_candidates_lead_id'), table_name='company_candidates')
    op.drop_index(op.f('ix_company_candidates_id'), table_name='company_candidates')
    op.drop_index(op.f('ix_company_candidates_current_stage_id'), table_name='company_candidates')
    op.drop_index(op.f('ix_company_candidates_created_by_user_id'), table_name='company_candidates')
    op.drop_index(op.f('ix_company_candidates_company_id'), table_name='company_candidates')
    op.drop_index(op.f('ix_company_candidates_candidate_id'), table_name='company_candidates')
    op.drop_table('company_candidates')
    op.drop_index(op.f('ix_candidate_applications_job_position_id'), table_name='candidate_applications')
    op.drop_index(op.f('ix_candidate_applications_id'), table_name='candidate_applications')
    op.drop_index(op.f('ix_candidate_applications_current_stage_id'), table_name='candidate_applications')
    op.drop_index(op.f('ix_candidate_applications_current_phase_id'), table_name='candidate_applications')
    op.drop_index(op.f('ix_candidate_applications_candidate_id'), table_name='candidate_applications')
    op.drop_index(op.f('ix_candidate_applications_application_status'), table_name='candidate_applications')
    op.drop_table('candidate_applications')
    op.drop_index(op.f('ix_workflow_stages_workflow_id'), table_name='workflow_stages')
    op.drop_index(op.f('ix_workflow_stages_order'), table_name='workflow_stages')
    op.drop_index(op.f('ix_workflow_stages_id'), table_name='workflow_stages')
    op.drop_table('workflow_stages')
    op.drop_index(op.f('ix_resumes_resume_type'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_candidate_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_interview_template_sections_status'), table_name='interview_template_sections')
    op.drop_index(op.f('ix_interview_template_sections_sort_order'), table_name='interview_template_sections')
    op.drop_index(op.f('ix_interview_template_sections_section'), table_name='interview_template_sections')
    op.drop_index(op.f('ix_interview_template_sections_interview_template_id'), table_name='interview_template_sections')
    op.drop_index(op.f('ix_interview_template_sections_id'), table_name='interview_template_sections')
    op.drop_table('interview_template_sections')
    op.drop_index(op.f('ix_custom_fields_id'), table_name='custom_fields')
    op.drop_index('ix_custom_fields_entity_customization_id', table_name='custom_fields')
    op.drop_table('custom_fields')
    op.drop_index(op.f('ix_company_user_company_roles_company_role_id'), table_name='company_user_company_roles')
    op.drop_index(op.f('ix_company_user_company_roles_company_user_id'), table_name='company_user_company_roles')
    op.drop_table('company_user_company_roles')
    op.drop_index(op.f('ix_company_roles_company_id'), table_name='company_roles')
    op.drop_index(op.f('ix_company_roles_id'), table_name='company_roles')
    op.drop_table('company_roles')
    op.drop_index(op.f('ix_company_users_user_id'), table_name='company_users')
    op.drop_index(op.f('ix_company_users_id'), table_name='company_users')
    op.drop_index(op.f('ix_company_users_company_id'), table_name='company_users')
    op.drop_table('company_users')
    op.drop_index(op.f('ix_candidate_projects_id'), table_name='candidate_projects')
    op.drop_table('candidate_projects')
    op.drop_index(op.f('ix_candidate_experiences_id'), table_name='candidate_experiences')
    op.drop_table('candidate_experiences')
    op.drop_index(op.f('ix_candidate_educations_id'), table_name='candidate_educations')
    op.drop_table('candidate_educations')
    op.drop_index(op.f('ix_workflows_workflow_type'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_status'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_phase_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_is_default'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_company_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_assets_user_id'), table_name='user_assets')
    op.drop_index(op.f('ix_user_assets_processing_status'), table_name='user_assets')
    op.drop_index(op.f('ix_user_assets_id'), table_name='user_assets')
    op.drop_index(op.f('ix_user_assets_asset_type'), table_name='user_assets')
    op.drop_table('user_assets')
    op.drop_index(op.f('ix_job_positions_visibility'), table_name='job_positions')
    op.drop_index(op.f('ix_job_positions_title'), table_name='job_positions')
    op.drop_index(op.f('ix_job_positions_stage_id'), table_name='job_positions')
    op.drop_index(op.f('ix_job_positions_public_slug'), table_name='job_positions')
    op.drop_index(op.f('ix_job_positions_job_position_workflow_id'), table_name='job_positions')
    op.drop_index(op.f('ix_job_positions_id'), table_name='job_positions')
    op.drop_index(op.f('ix_job_positions_company_id'), table_name='job_positions')
    op.drop_table('job_positions')
    op.drop_index(op.f('ix_job_position_workflows_status'), table_name='job_position_workflows')
    op.drop_index(op.f('ix_job_position_workflows_id'), table_name='job_position_workflows')
    op.drop_index(op.f('ix_job_position_workflows_company_id'), table_name='job_position_workflows')
    op.drop_table('job_position_workflows')
    op.drop_index(op.f('ix_interview_templates_type'), table_name='interview_templates')
    op.drop_index(op.f('ix_interview_templates_status'), table_name='interview_templates')
    op.drop_index(op.f('ix_interview_templates_name'), table_name='interview_templates')
    op.drop_index(op.f('ix_interview_templates_job_category'), table_name='interview_templates')
    op.drop_index(op.f('ix_interview_templates_id'), table_name='interview_templates')
    op.drop_index(op.f('ix_interview_templates_created_by'), table_name='interview_templates')
    op.drop_index('idx_type', table_name='interview_templates')
    op.drop_index('idx_status_type', table_name='interview_templates')
    op.drop_index('idx_job_category_status', table_name='interview_templates')
    op.drop_index('idx_created_by_status', table_name='interview_templates')
    op.drop_table('interview_templates')
    op.drop_index(op.f('ix_field_validation_rules_stage_id'), table_name='field_validation_rules')
    op.drop_index(op.f('ix_field_validation_rules_is_active'), table_name='field_validation_rules')
    op.drop_index(op.f('ix_field_validation_rules_custom_field_id'), table_name='field_validation_rules')
    op.drop_table('field_validation_rules')
    op.drop_index(op.f('ix_entity_customizations_id'), table_name='entity_customizations')
    op.drop_index('ix_entity_customizations_entity_type_id', table_name='entity_customizations')
    op.drop_index(op.f('ix_entity_customizations_entity_type'), table_name='entity_customizations')
    op.drop_index(op.f('ix_entity_customizations_entity_id'), table_name='entity_customizations')
    op.drop_table('entity_customizations')
    op.drop_index(op.f('ix_company_phases_workflow_type'), table_name='company_phases')
    op.drop_index(op.f('ix_company_phases_status'), table_name='company_phases')
    op.drop_index(op.f('ix_company_phases_sort_order'), table_name='company_phases')
    op.drop_index(op.f('ix_company_phases_id'), table_name='company_phases')
    op.drop_index(op.f('ix_company_phases_company_id'), table_name='company_phases')
    op.drop_table('company_phases')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_candidates_user_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_name'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
