"""Add company workflows and stages tables only

Revision ID: 468a891f5208
Revises: 6286cc5b7f24
Create Date: 2025-10-21 23:49:37.202888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '468a891f5208'
down_revision: Union[str, Sequence[str], None] = '6286cc5b7f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - Add company workflows and stages tables only."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create candidate_application_workflows table
    op.create_table('candidate_application_workflows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='workflowstatus', native_enum=False, length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_application_workflows_company_id'), 'candidate_application_workflows', ['company_id'], unique=False)
    op.create_index(op.f('ix_candidate_application_workflows_id'), 'candidate_application_workflows', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_application_workflows_is_default'), 'candidate_application_workflows', ['is_default'], unique=False)
    op.create_index(op.f('ix_candidate_application_workflows_status'), 'candidate_application_workflows', ['status'], unique=False)

    # Create workflow_stages table
    op.create_table('workflow_stages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('stage_type', sa.Enum('INITIAL', 'INTERMEDIATE', 'FINAL', 'CUSTOM', name='stagetype', native_enum=False, length=20), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('required_outcome', sa.Enum('PASSED', 'FAILED', 'PENDING', 'SKIPPED', name='stageoutcome', native_enum=False, length=20), nullable=True),
    sa.Column('estimated_duration_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['candidate_application_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_stages_id'), 'workflow_stages', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_stages_order'), 'workflow_stages', ['order'], unique=False)
    op.create_index(op.f('ix_workflow_stages_workflow_id'), 'workflow_stages', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - Remove company workflows and stages tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_stages_workflow_id'), table_name='workflow_stages')
    op.drop_index(op.f('ix_workflow_stages_order'), table_name='workflow_stages')
    op.drop_index(op.f('ix_workflow_stages_id'), table_name='workflow_stages')
    op.drop_table('workflow_stages')
    op.drop_index(op.f('ix_candidate_application_workflows_status'), table_name='candidate_application_workflows')
    op.drop_index(op.f('ix_candidate_application_workflows_is_default'), table_name='candidate_application_workflows')
    op.drop_index(op.f('ix_candidate_application_workflows_id'), table_name='candidate_application_workflows')
    op.drop_index(op.f('ix_candidate_application_workflows_company_id'), table_name='candidate_application_workflows')
    op.drop_table('candidate_application_workflows')
    # ### end Alembic commands ###
