"""Add interview questions, responses and history tables

Revision ID: 4beb07b3df8e
Revises: d091c2e822fe
Create Date: 2025-09-23 08:01:43.622469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4beb07b3df8e'
down_revision: Union[str, Sequence[str], None] = 'd091c2e822fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
