"""add company_pages table

Revision ID: 85d66f225618
Revises: f25e1cd38bbb
Create Date: 2025-11-09 10:37:46.136538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85d66f225618'
down_revision: Union[str, Sequence[str], None] = 'f25e1cd38bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_pages',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.String(length=255), nullable=False),
    sa.Column('page_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('plain_text', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('meta_keywords', sa.JSON(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_company_page_company_status', 'company_pages', ['company_id', 'status'], unique=False)
    op.create_index('idx_company_page_company_type', 'company_pages', ['company_id', 'page_type'], unique=False)
    op.create_index('idx_company_page_default', 'company_pages', ['company_id', 'page_type', 'is_default'], unique=False)
    op.create_index('idx_company_page_published', 'company_pages', ['company_id', 'status', 'published_at'], unique=False)
    op.create_index('idx_company_page_status', 'company_pages', ['status'], unique=False)
    op.create_table('file_attachments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_attachments_candidate_id'), 'file_attachments', ['candidate_id'], unique=False)
    # Note: company_roles and company_user_company_roles tables exist and should not be dropped
    # Note: job_position_stages indexes changes are handled separately
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_company_page_status', table_name='company_pages')
    op.drop_index('idx_company_page_published', table_name='company_pages')
    op.drop_index('idx_company_page_default', table_name='company_pages')
    op.drop_index('idx_company_page_company_type', table_name='company_pages')
    op.drop_index('idx_company_page_company_status', table_name='company_pages')
    op.drop_table('company_pages')
    op.drop_index(op.f('ix_file_attachments_candidate_id'), table_name='file_attachments')
    op.drop_table('file_attachments')
    # ### end Alembic commands ###
