"""

Revision ID: d091c2e822fe
Revises: 8ea7f0f899f6
Create Date: 2025-09-23 08:00:50.511147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd091c2e822fe'
down_revision: Union[str, Sequence[str], None] = '8ea7f0f899f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_templates', sa.Column('intro', sa.Text(), nullable=True))
    op.add_column('interview_templates', sa.Column('prompt', sa.Text(), nullable=True))
    op.add_column('interview_templates', sa.Column('goal', sa.Text(), nullable=True))
    op.add_column('interview_templates', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('interview_templates', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('interview_templates', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('interview_templates', 'status',
               existing_type=postgresql.ENUM('ENABLED', 'DRAFT', 'DISABLED', name='interviewtemplatestatus'),
               nullable=False)
    op.alter_column('interview_templates', 'type',
               existing_type=postgresql.ENUM('EXTENDED_PROFILE', 'POSITION_INTERVIEW', name='interviewtemplatetype'),
               nullable=False)
    op.create_index('idx_job_category_status', 'interview_templates', ['job_category', 'status'], unique=False)
    op.create_index('idx_section_type', 'interview_templates', ['section', 'type'], unique=False)
    op.create_index('idx_status_type', 'interview_templates', ['status', 'type'], unique=False)
    op.create_index(op.f('ix_interview_templates_job_category'), 'interview_templates', ['job_category'], unique=False)
    op.create_index(op.f('ix_interview_templates_section'), 'interview_templates', ['section'], unique=False)
    op.create_index(op.f('ix_interview_templates_status'), 'interview_templates', ['status'], unique=False)
    op.create_index(op.f('ix_interview_templates_type'), 'interview_templates', ['type'], unique=False)
    op.add_column('interviews', sa.Column('interview_type', sa.Enum('RESUME_ENHANCEMENT', 'JOB_APPLICATION', 'SCREENING', name='interviewtype'), nullable=False))
    op.add_column('interviews', sa.Column('membership_level', sa.Enum('BASIC', 'PREMIUM', 'ELITE', name='membershiplevel'), nullable=False))
    op.alter_column('interviews', 'candidate_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('interviews', 'status',
               existing_type=postgresql.ENUM('PENDING', 'IN_PROGRESS', 'PAUSED', 'DRAFT', 'COMPLETED', 'DISCARDED', name='interviewstatus'),
               nullable=False)
    op.alter_column('interviews', 'interview_template_type',
               existing_type=postgresql.ENUM('EXTENDED_PROFILE', 'POSITION_INTERVIEW', name='interviewtemplatetype'),
               nullable=False)
    op.alter_column('interviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('interviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index('idx_candidate_status', 'interviews', ['candidate_id', 'status'], unique=False)
    op.create_index('idx_created_status', 'interviews', ['created_at', 'status'], unique=False)
    op.create_index('idx_interview_type_membership', 'interviews', ['interview_type', 'membership_level'], unique=False)
    op.create_index(op.f('ix_interviews_candidate_id'), 'interviews', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_interviews_created_at'), 'interviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_interviews_interview_type'), 'interviews', ['interview_type'], unique=False)
    op.create_index(op.f('ix_interviews_membership_level'), 'interviews', ['membership_level'], unique=False)
    op.create_index(op.f('ix_interviews_status'), 'interviews', ['status'], unique=False)
    op.create_foreign_key(None, 'interviews', 'candidates', ['candidate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.drop_index(op.f('ix_interviews_status'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_membership_level'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_interview_type'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_created_at'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_candidate_id'), table_name='interviews')
    op.drop_index('idx_interview_type_membership', table_name='interviews')
    op.drop_index('idx_created_status', table_name='interviews')
    op.drop_index('idx_candidate_status', table_name='interviews')
    op.alter_column('interviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('interviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('interviews', 'interview_template_type',
               existing_type=postgresql.ENUM('EXTENDED_PROFILE', 'POSITION_INTERVIEW', name='interviewtemplatetype'),
               nullable=True)
    op.alter_column('interviews', 'status',
               existing_type=postgresql.ENUM('PENDING', 'IN_PROGRESS', 'PAUSED', 'DRAFT', 'COMPLETED', 'DISCARDED', name='interviewstatus'),
               nullable=True)
    op.alter_column('interviews', 'candidate_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('interviews', 'membership_level')
    op.drop_column('interviews', 'interview_type')
    op.drop_index(op.f('ix_interview_templates_type'), table_name='interview_templates')
    op.drop_index(op.f('ix_interview_templates_status'), table_name='interview_templates')
    op.drop_index(op.f('ix_interview_templates_section'), table_name='interview_templates')
    op.drop_index(op.f('ix_interview_templates_job_category'), table_name='interview_templates')
    op.drop_index('idx_status_type', table_name='interview_templates')
    op.drop_index('idx_section_type', table_name='interview_templates')
    op.drop_index('idx_job_category_status', table_name='interview_templates')
    op.alter_column('interview_templates', 'type',
               existing_type=postgresql.ENUM('EXTENDED_PROFILE', 'POSITION_INTERVIEW', name='interviewtemplatetype'),
               nullable=True)
    op.alter_column('interview_templates', 'status',
               existing_type=postgresql.ENUM('ENABLED', 'DRAFT', 'DISABLED', name='interviewtemplatestatus'),
               nullable=True)
    op.alter_column('interview_templates', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('interview_templates', 'updated_at')
    op.drop_column('interview_templates', 'created_at')
    op.drop_column('interview_templates', 'goal')
    op.drop_column('interview_templates', 'prompt')
    op.drop_column('interview_templates', 'intro')
    # ### end Alembic commands ###
