"""add_ai_fields_to_interview_table

Revision ID: d96e7c594548
Revises: 626bf3c5484d
Create Date: 2025-09-17 13:24:59.373981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd96e7c594548'
down_revision: Union[str, Sequence[str], None] = '626bf3c5484d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('progress_data', sa.JSON(), nullable=True))
    op.add_column('interviews', sa.Column('ai_context', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'ai_context')
    op.drop_column('interviews', 'progress_data')
    # ### end Alembic commands ###
