"""Job Position Application Commands"""
from src.company_bc.job_position.application.commands.job_position_status_commands import (
    RequestJobPositionApprovalCommand,
    RequestJobPositionApprovalCommandHandler,
    ApproveJobPositionCommand,
    ApproveJobPositionCommandHandler,
    RejectJobPositionCommand,
    RejectJobPositionCommandHandler,
    PublishJobPositionCommand,
    PublishJobPositionCommandHandler,
    HoldJobPositionCommand,
    HoldJobPositionCommandHandler,
    ResumeJobPositionCommand,
    ResumeJobPositionCommandHandler,
    CloseJobPositionCommand,
    CloseJobPositionCommandHandler,
    ArchiveJobPositionCommand,
    ArchiveJobPositionCommandHandler,
    RevertJobPositionToDraftCommand,
    RevertJobPositionToDraftCommandHandler,
    CloneJobPositionCommand,
    CloneJobPositionCommandHandler,
)

__all__ = [
    # Status transition commands
    "RequestJobPositionApprovalCommand",
    "RequestJobPositionApprovalCommandHandler",
    "ApproveJobPositionCommand",
    "ApproveJobPositionCommandHandler",
    "RejectJobPositionCommand",
    "RejectJobPositionCommandHandler",
    "PublishJobPositionCommand",
    "PublishJobPositionCommandHandler",
    "HoldJobPositionCommand",
    "HoldJobPositionCommandHandler",
    "ResumeJobPositionCommand",
    "ResumeJobPositionCommandHandler",
    "CloseJobPositionCommand",
    "CloseJobPositionCommandHandler",
    "ArchiveJobPositionCommand",
    "ArchiveJobPositionCommandHandler",
    "RevertJobPositionToDraftCommand",
    "RevertJobPositionToDraftCommandHandler",
    "CloneJobPositionCommand",
    "CloneJobPositionCommandHandler",
]
