name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  backend-quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Cache uv dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-uv-

    - name: Install dependencies
      run: |
        uv sync

    - name: Run linting
      run: |
        uv run flake8 src/ adapters/ --count --select=E9,F63,F7,F82 --show-source --statistics
        uv run flake8 src/ adapters/ --count --exit-zero --max-complexity=10 --max-line-length=150 --statistics

    - name: Run type checking
      run: uv run mypy src/ adapters/ --ignore-missing-imports